In [1]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
print(arr.shape)

(3, 3)


In [5]:
arr1=np.zeros(5)
arr2=np.zeros((3,3))
print(arr1)
print(arr2)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
identitymatrix=np.eye(5)
print(identitymatrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
ans=arr[1,0]
print(ans)

4


In [8]:
print(arr[1,:])

[4 5 6]


In [9]:
print(arr[:,1])

[2 5 8]


In [10]:
print(arr[:,-1])

[3 6 9]


In [11]:
print(arr[1:3,:])

[[4 5 6]
 [7 8 9]]


In [13]:
ranges=np.arange(10,21)
print(ranges)

[10 11 12 13 14 15 16 17 18 19 20]


In [15]:
transpose=arr.T
print(transpose)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [17]:
from numpy.linalg import det
matrix=np.array([[1,2,3],[0,1,4],[5,6,0]])
deter=det(matrix)
print(deter)

0.9999999999999987


In [18]:
diagonal=np.diagonal(arr)
print(diagonal)

[1 5 9]


In [19]:
m1=np.array([[1,2],[3,4]])
m2=np.array([[8,7],[6,9]])
add=m1+m2
sub=m1-m2
mul=m1*m2
matrix_mul=np.dot(m1,m2)
print("Add",add)
print("Sub",sub)
print("element_wise multiplication",mul)
print("matrix multiplication",matrix_mul)


Add [[ 9  9]
 [ 9 13]]
Sub [[-7 -5]
 [-3 -5]]
element_wise multiplication [[ 8 14]
 [18 36]]
matrix multiplication [[20 25]
 [48 57]]


In [20]:
random=np.random.randint(1,100,(3,5))
print(random)

[[20 63 36  3 40]
 [95 17 11 68 38]
 [81 93 28 70 80]]


In [22]:
lineararray=np.linspace(0,1,5)
print(lineararray)

[0.   0.25 0.5  0.75 1.  ]
